### ISSUE TITLE
Error in sniffing.Py 

### ISSUE THREAD

**Issue by Veto2922** [vladan-stojnic/ML-based-WAF#2]
![IMG20221108181554](https://user-images.githubusercontent.com/114834171/200618650-04b44884-228c-4f8c-badd-53ed957ee1f9.jpg)

Is there a solution to this problem please?

**Comment by vladan-stojnic** [comment]
Hi,

It seems you are having newer version of scikit-learn than the one that was used when project was created. In older versions sklearn used to have joblib in its externals. Now joblib should be installed as a separate package. Since I don't know how would the whole thing work with newer versions of libraries, I would recommend that you install libraries with versions specified in `requirements.txt`.
